name       : haskell-OpenGL
version    : 3.0.1.0
release    : 1
source     :
    - http://hackage.haskell.org/package/OpenGL-3.0.1.0/OpenGL-3.0.1.0.tar.gz : f45c0c65aa31108391d5d86bb65b3e945e0c1102b7d09db4b356c060f3afa2da
license    : BSD-3-Clause
component  : programming
summary    : A Haskell binding for the OpenGL graphics system (GL) and its accompanying utility library (GLU).
description: |
    A Haskell binding for the OpenGL graphics system (GL) and its accompanying utility library (GLU).
builddeps  :
    - pkgconfig(glu)
    - ghc
    - haskell-GLURaw
    - haskell-ObjectName
    - haskell-OpenGLRaw
    - haskell-StateVar
    - haskell-text
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 OpenGL-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/OpenGL-$version.conf
