name       : haskell-OpenGL
version    : 3.0.1.0
release    : 3
source     :
    - http://hackage.haskell.org/package/OpenGL-3.0.1.0/OpenGL-3.0.1.0.tar.gz : f45c0c65aa31108391d5d86bb65b3e945e0c1102b7d09db4b356c060f3afa2da
license    : BSD-3-Clause
component  : programming.haskell
summary    : A Haskell binding for the OpenGL graphics system (GL) and its accompanying
    utility library (GLU).
description: |
    A Haskell binding for the OpenGL graphics system (GL) and its accompanying utility library (GLU).
builddeps  :
    - pkgconfig(glu)
    - ghc
    - haskell-cabal-install
    - haskell-GLURaw
    - haskell-ObjectName
    - haskell-OpenGLRaw
    - haskell-StateVar
    - haskell-text
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
