name       : haskell-OpenGL
version    : 3.0.3.0
release    : 5
source     :
    - https://hackage.haskell.org/package/OpenGL-3.0.3.0/OpenGL-3.0.3.0.tar.gz : 5a05ffc752dfc7dd16818d7b3c7c59a27639e246cdfa1963fa02e3ce247a2e19
license    : BSD-3-Clause
component  : programming.haskell
summary    : A Haskell binding for the OpenGL graphics system (GL) and its accompanying utility library (GLU).
description: |
    A Haskell binding for the OpenGL graphics system (GL) and its accompanying utility library (GLU).
builddeps  :
    - haskell-cabal-install
    - haskell-GLURaw-devel
    - haskell-ObjectName-devel
    - haskell-StateVar-devel
rundeps    :
    - devel:
        - haskell-GLURaw-devel
        - haskell-ObjectName-devel
        - haskell-StateVar-devel
networking : yes
setup      : |
    sed -i "s|< 1.2|< 1.3|g" OpenGL.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
